mods.extendedcrafting.TableCrafting.addShaped("infinity_ingot", 0, <item:avaritia:infinity_ingot>, [
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);