mods.extendedcrafting.TableCrafting.addShaped("infinity_helmet", 0, <item:avaritia:infinity_helmet>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_chestplate", 0, <item:avaritia:infinity_chestplate>, [
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_pants", 0, <item:avaritia:infinity_pants>, [
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_boots", 0, <item:avaritia:infinity_boots>, [
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);