mods.extendedcrafting.TableCrafting.addShaped("neutron_collector", 0, <item:avaritia:neutron_collector>, [
	[<item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>], 
	[<item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:iron_block>], 
	[<item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:iron_block>], 
	[<item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:redstone_block>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:minecraft:redstone_block>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>], 
	[<item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:redstone_block>, <item:projecte:red_matter>, <item:avaritia:double_compressed_crafting_table>, <item:projecte:red_matter>, <item:minecraft:redstone_block>, <item:minecraft:air>, <item:minecraft:iron_block>], 
	[<item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:redstone_block>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:projecte:red_matter>, <item:minecraft:redstone_block>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>], 
	[<item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:redstone_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:iron_block>], 
	[<item:minecraft:iron_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:iron_block>], 
	[<item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:iron_block>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:iron_block>, <item:minecraft:iron_block>, <item:minecraft:iron_block>]
]);
mods.extendedcrafting.TableCrafting.addShaped("endest_pearl", 0, <item:avaritia:endest_pearl>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>, <item:minecraft:air>], 
	[<item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:avaritia:neutron_ingot>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>], 
	[<item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:avaritia:neutron_ingot>, <item:extendedcrafting:ender_star>, <item:avaritia:neutron_ingot>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>], 
	[<item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:avaritia:neutron_ingot>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>], 
	[<item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:end_stone>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("cosmic_meatballs", 0, <item:avaritia:cosmic_meatballs>, [
	[<item:avaritia:neutron_pile>, <item:minecraft:beef>, <item:minecraft:beef>, <item:minecraft:chicken>, <item:minecraft:chicken>, <item:minecraft:porkchop>, <item:minecraft:porkchop>, <item:minecraft:mutton>, <item:minecraft:mutton>], 
	[<item:minecraft:rabbit>, <item:minecraft:rabbit>, <item:minecraft:cod>, <item:minecraft:cod>, <item:minecraft:salmon>, <item:minecraft:salmon>, <item:pamhc2foodextended:swedishmeatballsitem>, <item:pamhc2foodextended:sweetandsourmeatballsitem>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("ultimate_stew", 0, <item:avaritia:ultimate_stew>, [
	[<item:avaritia:neutron_pile>, <item:pamhc2foodcore:noodlesoupitem>, <item:pamhc2foodcore:potatosoupitem>, <item:pamhc2foodcore:carrotsoupitem>, <item:pamhc2foodcore:pumpkinsoupitem>, <item:pamhc2foodextended:chickennoodlesoupitem>, <item:pamhc2foodextended:cactussoupitem>, <item:pamhc2foodextended:creamedbroccolisoupitem>, <item:pamhc2foodextended:creamofavocadosoupitem>], 
	[<item:pamhc2foodextended:splitpeasoupitem>, <item:pamhc2foodextended:tomatosoupitem>, <item:pamhc2foodextended:vegetablesoupitem>, <item:pamhc2foodextended:leekbaconsoupitem>, <item:pamhc2foodextended:oldworldveggiesoupitem>, <item:pamhc2foodextended:peaandhamsoupitem>, <item:pamhc2foodextended:pizzasoupitem>, <item:pamhc2foodextended:potatoandleeksoupitem>, <item:pamhc2foodextended:seedsoupitem>], 
	[<item:pamhc2foodextended:gardensoupitem>, <item:pamhc2foodextended:hotandsoursoupitem>, <item:pamhc2foodextended:lambbarleysoupitem>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("infinity_catalyst", 0, <item:avaritia:infinity_catalyst>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:avaritia:neutron>, <item:redstone_arsenal:flux_metal_block>, <item:avaritia:cosmic_meatballs>, <item:avaritia:ultimate_stew>, <item:avaritia:endest_pearl>, <item:botania:terrasteel_block>, <item:mekanism:block_refined_obsidian>, <item:chancecubes:chance_cube>], 
	[<item:pneumaticcraft:compressed_iron_block>, <item:immersiveengineering:storage_constantan>, <item:avaritia:record_fragment>, <item:avaritia:crystal_matrix>, <item:bigreactors:ludicrite_block>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:flux_star_block>, <item:cyclic:gem_obsidian>], 
	[<item:twilightforest:ironwood_block>, <item:extendedcrafting:crystaltine_block>, <item:betterfurnacesreforged:extreme_forge>, <item:thermal:phyto_tnt>, <item:extradisks:16384k_storage_part> | <item:megacells:cell_component_16m>, <item:projecte:red_matter_block>, <item:mysticalagradditions:insanium_block>, <item:aether:enchanted_gravitite>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("neutronium_solar_panel", 0, <item:solarflux:sp_avaritia.neutronium>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:solarflux:sp_de.draconic>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:solarflux:sp_de.draconic>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_pile>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_nugget>, <item:solarflux:sp_de.draconic>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:solarflux:sp_de.draconic>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);
mods.extendedcrafting.TableCrafting.addShaped("solar_panel_infinity", 0, <item:solarflux:sp_avaritia.infinity>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_pile>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_pile>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron>, <item:avaritia:neutron_nugget>, <item:avaritia:infinity_ingot>, <item:solarflux:sp_avaritia.neutronium>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_pile>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_pile>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);
