
#Server configuration for Ex Deorum
[server]
	#Whether players in a void world start out with a torch or not.
	starting_torch = false
	#Whether players in a void world start out with a full wooden watering can.
	starting_watering_can = false
	#Whether players can use multiple sieves in a 3x3 area at once.
	simultaneous_sieve_usage = true
	#Whether machines/fake players can interact with the Sieve.
	automated_sieves = true
	#The progress to increment by each tick for barrel composting and witch water transformation.
	#Range: 0.0 ~ 1.0
	barrel_progress_step = 0.004
	#Whether Witch Water forms netherrack when lava flows into it, allowing for a netherrack version of a cobblestone generator.
	witch_water_netherrack_generator = false
	#Whether the Void World type is used by default in the "server.properties" file when creating a server.
	set_void_world_as_default = false
	#The ID of the default tree feature to use when generating a spawn island (or when useBiomeAppropriateTree is true and the biome has no tree set). By default, minecraft:oak_tree_bees_005 is used.
	default_spawn_tree_feature = "minecraft:oak_tree_bees_005"
	#Whether the Spawn Tree in the void world changes based on the biome it's in. If false, Oak Tree is always used.
	use_biome_appropriate_tree = false
	#Whether to restrict Moss Block sieve drops to 1-2 items when sieving. May be useful when lots of mods add saplings and the sieve drops become spammy.
	limit_moss_sieve_drops = true
	#Whether glass bottles can be used to transfer water between water crucibles and barrels.
	allow_water_bottle_transfer = true
	#Whether the entity conversion mechanic of Witch Water is enabled. If enabled, when an entity steps into Witch Water, the following conversions may happen: Villager -> Zombie Villager, Cleric Villager -> Witch, Skeleton -> Wither Skeleton, Creeper -> Charged Creeper, Spider -> Cave Spider, Pig & Piglin -> Zombified Piglin, Squid -> Ghast, Mooshroom -> Brown Mooshroom, Axolotl -> Blue Axolotl, Rabbit -> Killer Rabbit, Pufferfish -> Guardian, Horse -> Skeleton/Zombie Horse
	allow_witch_water_entity_conversion = true

