import mods.jeitweaker.Jei;
import crafttweaker.api.text.Component;
Jei.addIngredientInformation(<item:ad_astra:oil_bucket>, Component.literal("Use biodiesel from Immersive Engineering or biodisel/diesel from Pneumatic Craft as rocket fuel."));
Jei.addIngredientInformation(<fluid:ad_astra:oil>, Component.literal("Use biodiesel from Immersive Engineering or biodisel/diesel from Pneumatic Craft as rocket fuel."));
Jei.addIngredientInformation(<item:ad_astra:fuel_bucket>, Component.literal("Use biodiesel from Immersive Engineering or biodisel/diesel from Pneumatic Craft as rocket fuel."));
Jei.addIngredientInformation(<fluid:ad_astra:fuel>, Component.literal("Use biodiesel from Immersive Engineering or biodisel/diesel from Pneumatic Craft as rocket fuel."));
Jei.addIngredientInformation(<item:mysticalagriculture:prosperity_shard>, Component.literal("Rare drop from sifting dust. Can be mined in the Nether and End. Craft from diamonds and a prismarine shard or use a Metallurgic Infuser for a cheaper option."));
Jei.addIngredientInformation(<item:cyclic:battery_infinite>, Component.literal("Not obtainable in survival mode."));
Jei.addIngredientInformation(<item:reliquary:alkahestry_tome>, Component.literal("Disabled in this pack."));
Jei.addIngredientInformation(<item:minecraft:crying_obsidian>, Component.literal("Obtained by finding ruined portals in the Nether, bartering with Piglins, or crafting using an Antiprotonic Nucleosynthesizer."));
Jei.addIngredientInformation(<item:mob_grinding_utils:golden_egg>, Component.literal("Obtained by feeding Nutritious Chicken Feed to a chicken."));
Jei.addIngredientInformation(<item:mob_grinding_utils:rotten_egg>, Component.literal("Obtained by feeding GM Chicken Feed Cursed to a chicken."));
Jei.addIngredientInformation(<item:thermal:watering_can>, Component.literal("The only watering can that can be used by fake players (click machine, item user). Limited water supply."));
Jei.addIngredientInformation(<item:avaritia:endest_pearl>, Component.literal("WARNING: Can cause severe damage to your base. Can kill any entity."));
Jei.addIngredientInformation(<item:toms_storage:ts.wireless_terminal>, Component.literal("Disabled in this pack. Use Applied Energistics or Refined Storage for a wireless storage option."));
Jei.addIngredientInformation(<item:toms_storage:ts.adv_wireless_terminal>, Component.literal("Disabled in this pack. Use Applied Energistics or Refined Storage for a wireless storage option."));
Jei.addIngredientInformation(<item:bigreactors:cyanite_ingot>, Component.literal("A byproduct of powering a Big Reactor with yellorium or uranium."));
Jei.addIngredientInformation(<fluid:exdeorum:witch_water>, Component.literal("Netherrack generator is disabled in this pack. Instead, mix Witch Water and Lava in a stone barrel to create netherrack (and reverse order to create blackstone). Witch Water can be also used in barrel mixing with sand to create soul sand."));
Jei.addIngredientInformation(<item:minecraft:netherite_upgrade_smithing_template>, Component.literal("This item is found in bastion remnants. Once obtained, it can be duplicated with a crafting recipe."));
Jei.addIngredientInformation(<fluid:bigreactors:rossinite>, Component.literal("Waste product from using Verderium as fuel in a reactor."));
Jei.addIngredientInformation(<fluid:bigreactors:magentite>, Component.literal("Waste product from using Bluetonium as fuel in a reactor."));
Jei.addIngredientInformation(<item:bigreactors:benitoite_crystal>, Component.literal("This item can be mined in the Nether."));
Jei.addIngredientInformation(<item:bigreactors:anglesite_crystal>, Component.literal("This item can be mined in the End."));
Jei.addIngredientInformation(<item:mekanism:dust_coal>, Component.literal("Hold some flint in your offhand and 3 or more coal in your main hand, then shift right-click a block of obsidian, crying obsidian or a grindstone to produce early powdered coal."));
Jei.addIngredientInformation(<item:avaritia:densest_neutron_collector>, Component.literal("Tier 4. Place in the world to collect neutron ingots at a faster rate. Cannot be sped up, as this is the maximum upgraded version."));
Jei.addIngredientInformation(<item:avaritia:denser_neutron_collector>, Component.literal("Tier 3. Place in the world to collect neutron ingots. Cannot be sped up, but can be used as a crafting ingredient to make an upgraded version."));
Jei.addIngredientInformation(<item:avaritia:dense_neutron_collector>, Component.literal("Tier 2. Place in the world to collect neutron nuggets. Cannot be sped up, but can be used as a crafting ingredient to make an upgraded version."));
Jei.addIngredientInformation(<item:avaritia:neutron_collector>, Component.literal("Tier 1. Place in the world to collect neutron piles. Cannot be sped up, but can be used as a crafting ingredient to make an upgraded version."));
Jei.addIngredientInformation(<item:mekanism:dust_lithium>, Component.literal("Lithium dust is created by putting Lithium into a Chemical Crystallizer. Lithium is made by putting Liquid Lithium into a Rotary Condensentrator. Liquid Lithium can be obtained by a Thermal Evaporation Plant using Brine."));
Jei.addIngredientInformation(<fluid:mekanism:lithium>, Component.literal("Lithium dust is created by putting Lithium into a Chemical Crystallizer. Lithium is made by putting Liquid Lithium into a Rotary Condensentrator. Liquid Lithium can be obtained by a Thermal Evaporation Plant using Brine."));
Jei.addIngredientInformation(<item:avaritia:neutron_pile>, Component.literal("Obtained via Neutron Collector. Remember, Neutron Collectors can be upgraded. There is a bug that prevents the EMC being removed from this item. Until a fix is found, to keep within the spirit of the pack, act as though this item has no EMC"));

